"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import type { ReorderList } from "@/lib/types";
import type { Role } from "@/lib/auth";
import { ReorderListStatusBadge } from "@/components/reorder/ReorderListStatusBadge";
import {
  markReorderDelivered,
  markReorderOrdered,
  updateReorderItemQty,
} from "@/lib/actions/reorder";

type ItemRow = {
  id: string;
  qty_at_generation: number;
  min_stock_level_at_generation: number;
  qty_to_order: number;
  item_status: string;
  product: { id: string; description: string; unit: string } | null;
  supplier: { id: string; name: string } | null;
};

export function ReorderDetailClient({
  list,
  initialItems,
  loadError,
  role,
}: {
  list: ReorderList;
  initialItems: ItemRow[];
  loadError: string | null;
  role: Role | null;
}) {
  const router = useRouter();
  const [items, setItems] = useState(initialItems);
  const [error, setError] = useState<string | null>(loadError);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const canEditQty = role === "purchasing_officer" && list.status === "draft";
  const canMarkOrdered = role === "purchasing_officer" && list.status === "draft";
  const canMarkDelivered = role === "storekeeper" && list.status === "ordered";

  async function handleQtyChange(itemId: string, value: string) {
    const qty = Number(value);
    setItems((prev) =>
      prev.map((i) => (i.id === itemId ? { ...i, qty_to_order: qty } : i)),
    );
  }

  async function handleQtyBlur(itemId: string, value: string) {
    const qty = Number(value);
    if (Number.isNaN(qty) || qty < 0) return;
    setSavingId(itemId);
    setError(null);
    const res = await updateReorderItemQty(itemId, qty);
    setSavingId(null);
    if ("error" in res) setError(res.error);
  }

  async function handleMarkOrdered() {
    if (!confirm("Mark this reorder list as Ordered?")) return;
    setBusy(true);
    setError(null);
    const res = await markReorderOrdered(list.id);
    setBusy(false);
    if ("error" in res) {
      setError(res.error);
      return;
    }
    router.refresh();
  }

  async function handleMarkDelivered() {
    if (
      !confirm(
        "Mark this reorder list as Delivered? Stock quantities will be incremented.",
      )
    )
      return;
    setBusy(true);
    setError(null);
    const res = await markReorderDelivered(list.id);
    setBusy(false);
    if ("error" in res) {
      setError(res.error);
      return;
    }
    router.refresh();
  }

  return (
    <div>
      <Link
        href="/reorder-lists"
        className="no-print text-sm text-neutral-500 hover:text-neutral-800"
      >
        ← All reorder lists
      </Link>

      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mt-2 mb-6">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-semibold text-neutral-900">
            Reorder List
          </h1>
          <ReorderListStatusBadge status={list.status} />
        </div>
        <div className="flex flex-wrap items-center gap-2">
          {canMarkOrdered && (
            <button
              onClick={handleMarkOrdered}
              disabled={busy}
              className="no-print px-4 py-2 rounded-md text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50"
            >
              {busy ? "Saving…" : "Mark as Ordered"}
            </button>
          )}
          {canMarkDelivered && (
            <button
              onClick={handleMarkDelivered}
              disabled={busy}
              className="no-print px-4 py-2 rounded-md text-sm font-medium bg-green-600 text-white hover:bg-green-700 disabled:opacity-50"
            >
              {busy ? "Saving…" : "Mark as Delivered"}
            </button>
          )}
          {list.status === "delivered" && (
            <span className="text-sm text-neutral-400">
              Delivered {new Date(list.delivered_at!).toLocaleString()}
            </span>
          )}
          <button
            onClick={() => window.print()}
            className="no-print px-4 py-2 rounded-md text-sm font-medium border border-neutral-300 text-neutral-700 hover:bg-neutral-50"
          >
            Print / PDF
          </button>
        </div>
      </div>

      {error && (
        <div className="mb-4 rounded-md border border-red-300 bg-red-50 text-red-800 px-4 py-3 text-sm flex justify-between items-start">
          <span>{error}</span>
          <button onClick={() => setError(null)} className="ml-4 text-red-500">
            &times;
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 text-sm">
        <div className="border border-neutral-200 rounded-lg p-3">
          <div className="text-neutral-400 text-xs uppercase">Generated By</div>
          <div className="text-neutral-800">{list.generated_by ?? "—"}</div>
        </div>
        <div className="border border-neutral-200 rounded-lg p-3">
          <div className="text-neutral-400 text-xs uppercase">Ordered By</div>
          <div className="text-neutral-800">
            {list.ordered_by ?? "—"}
            {list.ordered_at && (
              <span className="text-neutral-400">
                {" "}
                ({new Date(list.ordered_at).toLocaleDateString()})
              </span>
            )}
          </div>
        </div>
        <div className="border border-neutral-200 rounded-lg p-3">
          <div className="text-neutral-400 text-xs uppercase">Delivered By</div>
          <div className="text-neutral-800">
            {list.delivered_by ?? "—"}
            {list.delivered_at && (
              <span className="text-neutral-400">
                {" "}
                ({new Date(list.delivered_at).toLocaleDateString()})
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="border border-neutral-200 rounded-lg overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-neutral-50 text-neutral-500 text-xs uppercase tracking-wide">
            <tr>
              <th className="text-left px-4 py-3 font-medium">Product</th>
              <th className="text-left px-4 py-3 font-medium">Supplier</th>
              <th className="text-right px-4 py-3 font-medium">
                Qty at Generation
              </th>
              <th className="text-right px-4 py-3 font-medium">Min Stock</th>
              <th className="text-right px-4 py-3 font-medium">
                Qty to Order
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-neutral-100">
            {items.map((item) => (
              <tr key={item.id} className="hover:bg-neutral-50">
                <td className="px-4 py-3 font-medium text-neutral-900">
                  {item.product?.description ?? "—"}
                </td>
                <td className="px-4 py-3 text-neutral-600">
                  {item.supplier?.name ?? "—"}
                </td>
                <td className="px-4 py-3 text-right tabular-nums">
                  {item.qty_at_generation} {item.product?.unit}
                </td>
                <td className="px-4 py-3 text-right tabular-nums text-neutral-500">
                  {item.min_stock_level_at_generation}
                </td>
                <td className="px-4 py-3 text-right">
                  {canEditQty ? (
                    <input
                      type="number"
                      min={0}
                      value={item.qty_to_order}
                      onChange={(e) =>
                        handleQtyChange(item.id, e.target.value)
                      }
                      onBlur={(e) => handleQtyBlur(item.id, e.target.value)}
                      disabled={savingId === item.id}
                      className="w-24 text-right rounded-md border border-neutral-300 px-2 py-1"
                    />
                  ) : (
                    <span className="tabular-nums">{item.qty_to_order}</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
