import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { ReorderListStatusBadge } from "@/components/reorder/ReorderListStatusBadge";

export const dynamic = "force-dynamic";

export default async function ReorderListsPage() {
  const supabase = await createClient();
  const { data: lists, error } = await supabase
    .from("reorder_lists")
    .select("*, reorder_list_items(id)")
    .order("created_at", { ascending: false });

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-semibold text-neutral-900">
          Reorder Lists
        </h1>
        <Link
          href="/reorder-lists/deliveries"
          className="px-4 py-2 rounded-md text-sm font-medium border border-neutral-300 text-neutral-700 hover:bg-neutral-50"
        >
          Delivery Summary
        </Link>
      </div>

      {error && (
        <div className="mb-4 rounded-md border border-red-300 bg-red-50 text-red-800 px-4 py-3 text-sm">
          {error.message}
        </div>
      )}

      {!lists || lists.length === 0 ? (
        <div className="text-center py-16 border border-dashed border-neutral-300 rounded-lg">
          <p className="text-neutral-500">
            No reorder lists yet — generate one from the Products page
          </p>
        </div>
      ) : (
        <div className="border border-neutral-200 rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-neutral-50 text-neutral-500 text-xs uppercase tracking-wide">
              <tr>
                <th className="text-left px-4 py-3 font-medium">Created</th>
                <th className="text-left px-4 py-3 font-medium">Status</th>
                <th className="text-right px-4 py-3 font-medium">Items</th>
                <th className="text-left px-4 py-3 font-medium">Generated By</th>
                <th className="text-right px-4 py-3 font-medium"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100">
              {lists.map((list) => (
                <tr key={list.id} className="hover:bg-neutral-50">
                  <td className="px-4 py-3 text-neutral-600 whitespace-nowrap">
                    {new Date(list.created_at).toLocaleString()}
                  </td>
                  <td className="px-4 py-3">
                    <ReorderListStatusBadge status={list.status} />
                  </td>
                  <td className="px-4 py-3 text-right tabular-nums">
                    {list.reorder_list_items?.length ?? 0}
                  </td>
                  <td className="px-4 py-3 text-neutral-600">
                    {list.generated_by ?? "—"}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link
                      href={`/reorder-lists/${list.id}`}
                      className="text-neutral-600 hover:text-neutral-900 font-medium"
                    >
                      View →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
